# Generated by Django 4.1.4 on 2022-12-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo')),
                ('carousel1', models.ImageField(upload_to='carousel')),
                ('carousel2', models.ImageField(upload_to='carousel')),
                ('carousel3', models.ImageField(upload_to='carousel')),
                ('carousel4', models.ImageField(upload_to='carousel')),
                ('carousel5', models.ImageField(upload_to='carousel')),
                ('carousel6', models.ImageField(upload_to='carousel')),
                ('carousel7', models.ImageField(upload_to='carousel')),
                ('carousel8', models.ImageField(upload_to='carousel')),
                ('aboutbanner', models.ImageField(upload_to='banner')),
                ('servicebanner', models.ImageField(upload_to='banner')),
                ('careerbanner', models.ImageField(upload_to='banner')),
                ('abouttitle', models.CharField(max_length=200)),
                ('abouttext', models.TextField()),
                ('aboutimg', models.ImageField(upload_to='pix')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pix', models.ImageField(upload_to='pix')),
                ('description', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
