# Generated by Django 4.1.4 on 2022-12-13 11:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeprofile',
            name='abouttext',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
