# Generated by Django 4.1.4 on 2022-12-13 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_homeprofile_abouttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
