# Generated by Django 4.1.4 on 2022-12-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_location_description_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
    ]
