# Generated by Django 4.1.4 on 2022-12-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
    ]
