# Generated by Django 4.1.4 on 2022-12-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_service_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='note',
        ),
    ]
