# Generated by Django 4.1.4 on 2022-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_service_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeprofile',
            name='email1',
            field=models.EmailField(default='mmg@gm.com', max_length=100),
        ),
        migrations.AddField(
            model_name='homeprofile',
            name='email2',
            field=models.EmailField(default='mmg@gm.com', max_length=100),
        ),
        migrations.AddField(
            model_name='homeprofile',
            name='fax',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='homeprofile',
            name='phone',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
