# Generated by Django 4.1.4 on 2022-12-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homeprofile_email1_homeprofile_email2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeprofile',
            name='email1',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homeprofile',
            name='email2',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homeprofile',
            name='fax',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homeprofile',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
