# Generated by Django 4.1.4 on 2022-12-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_homeprofile_email1_alter_homeprofile_email2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='columbia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='maryland',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='virginia',
            field=models.BooleanField(default=True),
        ),
    ]
