# Generated by Django 4.1.4 on 2022-12-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_service_columbia_service_maryland_service_virginia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='columbia',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='maryland',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='virginia',
            field=models.BooleanField(),
        ),
    ]
