# Generated by Django 4.1.4 on 2022-12-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_service_servicess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='servicess',
            field=models.BooleanField(),
        ),
    ]
