# Generated by Django 4.1.4 on 2022-12-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_service_servicess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('shift_applied_dc', models.CharField(blank=True, max_length=20, null=True)),
                ('shift_applied_maryland', models.CharField(blank=True, max_length=20, null=True)),
                ('shift_applied_virginia', models.CharField(blank=True, max_length=20, null=True)),
                ('high_school_or_ged', models.CharField(blank=True, max_length=20, null=True)),
                ('date_attended_from', models.CharField(blank=True, max_length=20, null=True)),
                ('date_attended_to', models.CharField(blank=True, max_length=20, null=True)),
                ('college_graduate', models.CharField(blank=True, max_length=20, null=True)),
                ('college_graduate_from', models.CharField(blank=True, max_length=20, null=True)),
                ('college_graduate_to', models.CharField(blank=True, max_length=20, null=True)),
                ('eligible_in_the_us', models.CharField(blank=True, max_length=20, null=True)),
                ('convicted', models.CharField(blank=True, max_length=20, null=True)),
                ('convicted_explain', models.TextField(blank=True, max_length=20, null=True)),
                ('violation', models.CharField(blank=True, max_length=20, null=True)),
                ('violation_explain', models.TextField(blank=True, max_length=20, null=True)),
                ('current_physical', models.CharField(blank=True, max_length=20, null=True)),
                ('current_physical_upload', models.FileField(upload_to='physical')),
                ('tbtest', models.CharField(blank=True, max_length=20, null=True)),
                ('tbtest_upload', models.FileField(upload_to='tbtest')),
                ('cpr_card', models.CharField(blank=True, max_length=20, null=True)),
                ('cpr_card_upload', models.FileField(upload_to='cpr')),
                ('first_aide_card', models.CharField(blank=True, max_length=20, null=True)),
                ('first_aide_upload', models.FileField(upload_to='firstaide')),
                ('resume', models.FileField(upload_to='resume')),
                ('message', models.TextField()),
                ('sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StateApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
