# Generated by Django 4.1.4 on 2022-12-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_career_positionapplied_state_stateapplied_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='zip',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
