# Generated by Django 4.1.4 on 2022-12-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_career_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
