# Generated by Django 4.1.4 on 2022-12-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_career_cell_number_career_position_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cell_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='position_applied',
            field=models.CharField(max_length=50),
        ),
    ]
