# Generated by Django 4.1.4 on 2022-12-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_career_cell_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='state_applied',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
