# Generated by Django 4.1.4 on 2022-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_career_state_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='state_applied',
            field=models.CharField(max_length=50),
        ),
    ]
